name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches: ["main"]  # Chạy khi có push lên main
  workflow_dispatch:  # Cho phép chạy thủ công từ Actions tab

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd docs
          npm install

      - name: Build Docusaurus
        run: |
          cd docs
          npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3  # Đổi sang hành động phù hợp với GitHub Pages
        with:
          path: docs/build  # Đảm bảo đường dẫn đúng với output của build

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
