name: Build and Push Docker Images

on:
  push:
    branches:
      - 4-devops-setting-up-a-cicd-pipeline  # Thay đổi thành nhánh bạn muốn theo dõi

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      MONGO_INITDB_DATABASE: ${{ secrets.MONGO_INITDB_DATABASE }}
      MONGO_INITDB_ROOT_USERNAME: ${{ secrets.MONGO_INITDB_ROOT_USERNAME }}
      MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}
      SPRING_DATA_MONGODB_URI: ${{ secrets.SPRING_DATA_MONGODB_URI }}

      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}

      PGADMIN_DEFAULT_EMAIL: ${{ secrets.PGADMIN_DEFAULT_EMAIL }}
      PGADMIN_DEFAULT_PASSWORD: ${{ secrets.PGADMIN_DEFAULT_PASSWORD }}

      MONGO_EXPRESS_USERNAME: ${{ secrets.MONGO_EXPRESS_USERNAME }}
      MONGO_EXPRESS_PASSWORD: ${{ secrets.MONGO_EXPRESS_PASSWORD }}

      EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}

      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

      CONFIG_SERVICE_URL: https://config-service-latest-s9vr.onrender.com # Đặt URL Config Server của bạn
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Verify Docker Login
        run: docker info | grep Username

      - name: Make Gradle Wrapper Executable
        run: chmod +x */gradlew
        
      - name: Build and Push Docker Images with Docker Compose
        run: |
          docker compose version
          docker compose build --parallel
          docker compose push

      - name: Download Render CLI
        run: |
          curl -L https://github.com/render-oss/cli/releases/download/v1.1.0/cli_1.1.0_linux_amd64.zip -o render.zip
          unzip -o render.zip
          sudo mv cli_v1.1.0 /usr/local/bin/render
          sudo chmod +x /usr/local/bin/render

      - name: Login to Render CLI
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: render login --api-key $RENDER_API_KEY

      - name: Set Render Workspace
        run: render workspace set ${{ secrets.RENDER_WORKSPACE_ID }} --confirm

      - name: Deploy Services to Render
        run: |
          render deploys create ${{ secrets.RENDER_SERVICE_ID_CONFIG_SERVICE }} --confirm
          render deploys create ${{ secrets.RENDER_SERVICE_ID_DISCOVERY_SERVICE }} --confirm
          render deploys create ${{ secrets.RENDER_SERVICE_ID_GATEWAY_SERVICE }} --confirm
          render deploys create ${{ secrets.RENDER_SERVICE_ID_USER_SERVICE }} --confirm
          render deploys create ${{ secrets.RENDER_SERVICE_ID_BOOK_SERVICE }} --confirm
          render deploys create ${{ secrets.RENDER_SERVICE_ID_BORROWING_SERVICE }} --confirm
          render deploys create ${{ secrets.RENDER_SERVICE_ID_INVENTORY_SERVICE }} --confirm
          render deploys create ${{ secrets.RENDER_SERVICE_ID_NOTIFICATION_SERVICE }} --confirm

